# Generated by Django 3.0 on 2019-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_available',
            new_name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
