# Generated by Django 3.0 on 2019-12-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191207_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='return_date',
            new_name='drop_off_date',
        ),
    ]
