# Generated by Django 3.0 on 2019-12-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191208_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_date',
            new_name='pick_up_date',
        ),
    ]
