# Generated by Django 3.0 on 2019-12-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191208_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('people-carrier', 'people-carrier'), ('Estate', 'Estate'), ('luxury', 'luxury'), ('SUV', 'SUV')], max_length=20, null=True),
        ),
    ]
