# Generated by Django 3.0 on 2019-12-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191208_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Booking'},
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Estate', 'Estate'), ('luxury', 'luxury'), ('SUV', 'SUV')], max_length=20, null=True),
        ),
    ]
